auth:
  header: Authorization
  jwt:
    secret: semyon_secret
    exp:
      access: 300000
      refresh: 2592000000

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jta:
    enabled: true

app:
  registration:
    code:
      exp: 600000
  premium:
    snooper:
      exp: 600000