auth:
  header: Authorization
  jwt:
    secret: semyon_secret
    exp:
      access: 120000
      refresh: 240000

spring:
  data:
    postgres:
      host: localhost
      port: 5432
      database: around-db
      username: postgres
      password: password2